spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url:  jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver